# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install terraform
      env: 
          terraform_version: "1.0.3"
      run: |
        tf_version=$terraform_version
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip terraform_"$tf_version"_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        secret_token: ${{ secrets.AWS_SESSION_TOKEN }}
      working-directory: ./terraform-app
      run: terraform init -input=false

    - name: Terraform validation
      working-directory: ./terraform-app
      run: terraform validate

    - name: Terraform apply
      env:
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        secret_token: ${{ secrets.AWS_SESSION_TOKEN }}
      working-directory: ./terraform-app
      run: terraform apply -auto-approve -input=false
